repos:
  - repo: local
    hooks:
      - id: shfmt
        name: shfmt
        minimum_pre_commit_version: 2.4.0
        language: system
        entry: shfmt
        args: [-i=2, -ci, -w]
        types: [shell]
      - id: shellcheck
        name: shellcheck
        language: system
        types: [shell]
        entry: bash
        args:
          [-c, "shfmt -f $(git rev-parse --show-toplevel) | xargs shellcheck"]
      - id: stylua
        name: StyLua
        language: rust
        entry: stylua
        types: [lua]
        args: ['-']
      - id: luacheck
        name: luacheck
        language: system
        entry: luacheck
        types: [lua]
        args: [.]
