name: install
on:
  push:
    branches: '**'
  pull_request:
    branches:
      - 'master'
      - 'release-[0-9]+.[0-9]+'

jobs:
  unixish:
    name: ${{ matrix.os }} ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - runner: ubuntu-20.04
            os: linux
          - runner: macos-10.15
            os: osx
    runs-on: ${{ matrix.runner }}
    if: github.event.pull_request.draft == false
    steps:
      - uses: actions/checkout@v2
      
      - name: Install dependencies for Linux
        if: matrix.os == 'linux'
        run: |
          sudo apt-get install -y gettext libtool libtool-bin autoconf automake cmake g++ pkg-config unzip build-essential
          sudo bash ./utils/bin/install-latest-neovim

      - name: Installl dependencies for OSX
        if: matrix.os == 'osx'
        run: |
          brew update >/dev/null
          brew upgrade
          brew install neovim

      - name: Install LunarVim
        run: |
          bash ./utils/installer/install.sh

      - name: Test LunarVim PackerCompile
        run: if nvim --headless +PackerCompile -c ':qall' 2>&1|grep -q 'Error'; then false; fi

      - name: Test LunarVim Health
        run: if nvim --headless +checkhealth -c ':qall' 2>&1|grep -q 'Error'; then false; fi

  freebsd:
    runs-on: macos-latest
    continue-on-error: true # we don't support freebsd yet
    name: "FreeBSD macos-latest"
    steps:
      - uses: actions/checkout@v2
      
      - name: Install dependencies for FreeBSD
        uses: vmactions/freebsd-vm@v0.1.5
        with:
          prepare: pkg install -y curl neovim
          run: bash ./utils/installer/install.sh

      - name: Test LunarVim PackerCompile
        uses: vmactions/freebsd-vm@v0.1.5
        with:
          run: if nvim --headless +PackerCompile -c ':qall' 2>&1|grep -q 'Error'; then false; fi

      - name: Test LunarVim Health
        uses: vmactions/freebsd-vm@v0.1.5
        with:
          run: if nvim --headless +checkhealth -c ':qall' 2>&1|grep -q 'Error'; then false; fi

