name: plugins-version-bump

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: false
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
  schedule:
    # note: this will keep updating the existing branch
    - cron: "0 10-14 * * 0,6"
    - cron: "0 14 * * 1-5"

jobs:
  plugins-version-bump:
    if: github.repository_owner == 'LunarVim'
    runs-on: ubuntu-latest
    continue-on-error: false
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v3

      - name: Install neovim binary
        uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: stable

      - name: Install LunarVim
        timeout-minutes: 4
        run: |
          ./utils/installer/install.sh --local --no-install-dependencies

      - name: run upgrade script
        run: make generate_new_lockfile

      - name: Re-install LunarVim
        timeout-minutes: 4
        run: |
          ./utils/installer/uninstall.sh --remove-backups --remove-config
          ./utils/installer/install.sh --local --no-install-dependencies

      - name: Run unit-tests
        # NOTE: make sure to adjust the timeout if you start adding a lot of tests
        timeout-minutes: 4
        run: make test

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          branch: plugins-bump
          delete-branch: true # Delete the branch when closing pull requests, and when undeleted after merging.
          token: ${{ secrets.GITHUB_TOKEN }}
          author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          title: "chore: bump plugins version"
          commit-message: "chore: bump plugins version"
